### ISSUE TITLE
Unused contigs

### ISSUE THREAD

**Issue by JennyHTLee** [ucrbioinfo/Novo_Stitch#2]
Hello,

I stitched my assembled contigs and bionano map using Novo_Stitch. The stitched output aligned much better to my reference genome, but the total size is also a bit smaller than my original contigs. From my understanding, Novo_Stitch only process the aligned contigs, the size difference is therefore explainable. 

I want to know is it possible to recover the contigs that are not used (maybe unaligned and also low confidence?)? There is a fasta called "input_contigs_unaligned.fasta" in my iteration_1 folder, is this what I am after? The headers of these sequences are renamed to "SEQ" but I assume I can grep the sequences from my original contigs?

Thanks a lot!

Cheers,
Jenny

**Comment by pwhhero** [comment]
Hi Jenny,
You are right. Novo&Stitch only process the contigs which are aligned with high enough confidence. 
I think you need to look at "input_contigs_unaligned.fasta" and "input_contigs_lowconf.fasta" files which contain unaligned contigs and contigs aligned with low confidence respectively. Neither of these two groups of contigs is used to stitch. 

Best,
Weihua

**Comment by JennyHTLee** [comment]
Hi Weihua,

Great, thanks!

Cheers,
Jenny
