### ISSUE TITLE
chimeric contigs from adjusted step

### ISSUE THREAD

**Issue by njaupan** [ucrbioinfo/Novo_Stitch#3]
Hi,
I have two contigs assembled via canu, flye seperately. I did dotplot of whole genome alignment for stitched contigs vs non-stitch contigs aganist reference genome to check stitch quality:
even tough it reduced contigs number but it shows the chimeric contigs bewteen chr4 and chr5 in final stitched contigs, before it shows perfect continuity for canu assembled contigs and flye assembled contigs (straight line)
Do you know why?
 
Best,
panpan
![map_last_stitched_to_full_tair10 1_genomic](https://user-images.githubusercontent.com/8072119/50240156-579ea980-03c4-11e9-9f9d-06aaa4ddaa79.png)

**Comment by pwhhero** [comment]
Hi Panpan, 
Thanks for your interest in Novo&Stitch. For your question, stitching is actually a tradeoff between contiguity and correctness. Although we tried our best to avoid introducing new mis-joins in stitch when we designed this tool, we still cannot 100% promise Novo&Stitch will never generate chimeric contigs. In Novo&Stitch, there is a parameter "-e" which can adjust the tradeoff. If you set it larger, the number of chimeric contigs will be reduced but the contiguity will be reduced too. You could also try correct the chimeric contigs by yourself. You could map the input contigs to the final stitched contigs to know which contigs are misjoined into the chimeric contig. Then you can manually replace the chimeric contig by these input contigs corresponding to it. 

Best, 
Weihua
