### ISSUE TITLE
installing refaligner

### ISSUE THREAD

**Issue by lalalagartija** [ucrbioinfo/Novo_Stitch#4]
Hi, 

It seams like refaligner is no longer available on http://www.bnxinstall.com/RefalignerAssembler/Linux/
I can't find it anywhere else. Do you know where I could get it from ?

**Comment by StefanoLonardi** [comment]
Here
https://www.cs.ucr.edu/~stelo/refaligner/
There are three versions, depending on the type of CPU you have. You can try them all and find the one that works.
